# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions

#  phpstan:
#    name: PHPStan
#    runs-on: ubuntu-18.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: PHPStan
#        uses: docker://oskarstark/phpstan-ga
#        with:
#          args: analyse -l max -c phpstan.neon ./src
#          secrets: "GITHUB_TOKEN"

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run --allow-risky=yes
          secrets: "GITHUB_TOKEN"

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-18.04
    services:
        mysql:
            image: mysql:5.7
            env:
                MYSQL_ROOT_PASSWORD: geheim
            ports:
                - 3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: composer install
        run: "composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader"

      - name: run tests
        run: "php vendor/bin/phpunit"

#  phpunit:
#      name: PHPUnit
#      runs-on: ubuntu-18.04
#      steps:
#          - name: Checkout code
#            uses: actions/checkout@v2
#
#          - name: Install Dependencies
#            uses: php-actions/composer@v1 # or alternative dependency management
#
#          - name: PHPUnit tests
#            uses: php-actions/phpunit@v1
#            with:
#                config: phpunit.xml.dist
#                memory: 256M

  eslint:
    name: eslint
    runs-on: ubuntu-18.04
    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: eslint
          uses: reviewdog/action-eslint@v1
          with:
              github_token: ${{ secrets.github_token }}
              eslint_flags: 'assets/js'
