# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions

#  phpstan:
#    name: PHPStan
#    runs-on: ubuntu-18.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: PHPStan
#        uses: docker://oskarstark/phpstan-ga
#        with:
#          args: analyse -l max -c phpstan.neon ./src
#          secrets: "GITHUB_TOKEN"

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run --allow-risky=yes
          secrets: "GITHUB_TOKEN"

  cypress:
      name: cypress
      runs-on: ubuntu-18.04
      services:
          mysql:
              image: mysql:5.7
              env:
                  MYSQL_ROOT_PASSWORD: password
              ports:
                  - 3306
              options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

          maildev:
              image: djfarrelly/maildev
              ports:
                  - 1080
                  - 1025

      steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: '7.4'
                tools: composer

          - name: Run make init
            run: "make init"
            env:
                DATABASE_URL: mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/app_test?serverVersion=5.7

          - name: Install symfony cli
            run: "curl -sS https://get.symfony.com/cli/installer | bash"

          - name: run symfony web-server
            run: "/home/runner/.symfony/bin/symfony server:start -d"
            env:
                DATABASE_URL: mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/app_test?serverVersion=5.7
                MAILER_DSN: smtp://127.0.0.1:${{ job.services.maildev.ports['1025'] }}

          - name: Cypress run
            uses: cypress-io/github-action@v1
            env:
                CYPRESS_MAILER_BASE_URL: http://localhost:1080
                CYPRESS_BASE_URL: http://127.0.0.1:8000

          - uses: actions/upload-artifact@v1
            if: always()
            with:
                name: cypress-videos
                path: cypress/videos

          - uses: actions/upload-artifact@v1
            if: failure()
            with:
                name: sf-logs
                path: var/log

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-18.04
    services:
        mysql:
            image: mysql:5.7
            env:
                MYSQL_ROOT_PASSWORD: password
            ports:
                - 3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: composer install
        run: "composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader"

      - name: run tests
        run: "php vendor/bin/phpunit"
        env:
            DATABASE_URL: mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/app_test?serverVersion=5.7

  eslint:
    name: eslint
    runs-on: ubuntu-18.04
    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: eslint
          uses: reviewdog/action-eslint@v1
          with:
              github_token: ${{ secrets.github_token }}
              eslint_flags: 'assets/js'
